export type { CatalogCountryOptions } from '../../domain/catalog/country-options';
export type { ModelCatalogEntry } from '../../domain/catalog/model';
export type { DeviceInfo } from '../../domain/device/info';
export type { CatalogFirmwareLookupResult } from '../../domain/firmware/catalog-lookup-result';
export type { ReadSupportFirmwareLookupResult } from '../../domain/firmware/read-support-lookup-result';
export type { FirmwareVariant } from '../../domain/firmware/variant';
export {
  createDesktopRpcClient,
  type DesktopBridgeWindowGlobals,
} from './bridge';
export { createDesktopApiFromInvoker, type DesktopRpcInvoker } from './client';
export type {
  AppInfo,
  BackupRestoreAppEntry,
  BackupRestoreContactEntry,
  BackupRestoreFileEntry,
  BackupRestoreMediaEntry,
  BackupRestoreMessageEntry,
  BackupRestoreSnapshot,
  DesktopIntegrationStatus,
  DownloadProgressMessage,
  FirmwareTaskStatus,
  FrameworkUpdateInfo,
  LocalDownloadedFile,
  PlayStoreAppDetails,
  PlayStoreArch,
  PlayStoreDownloadedArtifact,
  PlayStoreDownloadGroup,
  PlayStoreSearchResult,
  RescueConsoleTone,
  RescueFlashTransport,
  RescueQdlStorage,
} from './entries';
export type {
  AttachLocalRecipeFromModelRequest,
  AttachLocalRecipeMetadataRequest,
  AuthCompleteRequest,
  BackupConnectedDeviceRequest,
  CancelDownloadRequest,
  DeleteBackupSnapshotRequest,
  DeleteLocalFileRequest,
  DesktopApi,
  DiscoverCountryOptionsRequest,
  DownloadFirmwareRequest,
  ExtractLocalFirmwareRequest,
  GetCatalogModelsRequest,
  LookupCatalogManualRequest,
  LookupConnectedDeviceFirmwareFromDeviceInfoRequest,
  LookupReadSupportByImeiRequest,
  LookupReadSupportByParamsRequest,
  LookupReadSupportBySnRequest,
  PauseDownloadRequest,
  PlayStoreAppDetailsRequest,
  PlayStoreDeleteDownloadRequest,
  PlayStoreDownloadRequest,
  PlayStoreInstallRequest,
  PlayStoreSearchRequest,
  ReadLocalFileContentRequest,
  ReadSupportHintsRequest,
  RescueLiteFirmwareFromLocalRequest,
  RescueLiteFirmwareRequest,
  RestoreBackupSnapshotRequest,
  ResumeDownloadRequest,
  SetDesktopPromptPreferenceRequest,
} from './requests';
export type {
  AttachLocalRecipeResponse,
  AuthCompleteResponse,
  AuthStartResponse,
  BackupConnectedDeviceResponse,
  BackupRestoreSnapshotsResponse,
  BridgePingResponse,
  CancelDownloadResponse,
  CatalogModelsResponse,
  ConnectedBackupPreviewProgressResponse,
  ConnectedBackupPreviewResponse,
  ConnectedLookupResponse,
  CountryOptionsResponse,
  DeleteBackupSnapshotResponse,
  DownloadFirmwareResponse,
  ExtractLocalFirmwareResponse,
  LocalDownloadedFilesResponse,
  ManualCatalogLookupResponse,
  PendingAuthCallbackResponse,
  PlayStoreAppDetailsResponse,
  PlayStoreDeleteDownloadResponse,
  PlayStoreDownloadResponse,
  PlayStoreDownloadsResponse,
  PlayStoreInstallResponse,
  PlayStoreSearchResponse,
  PlayStoreStatusResponse,
  ReadLocalFileContentResponse,
  ReadSupportHintsResponse,
  ReadSupportLookupResponse,
  RescueLiteFirmwareResponse,
  RestoreBackupSnapshotResponse,
  StoredAuthStateResponse,
  WindowsMtkDriverInstallResponse,
  WindowsQdloaderDriverInstallResponse,
  WindowsQdloaderDriverStatusResponse,
  WindowsSpdDriverInstallResponse,
} from './responses';
